apiVersion: v1
kind: Secret
metadata:
  name: courtstars-secret
  namespace: courtstars
type: Opaque
stringData:
  DB_USER: root
  DB_PASS: courtstars_root_password
  MYSQL_ROOT_PASSWORD: courtstars_root_password

