apiVersion: v1
kind: Service
metadata:
  name: courtstars-mysql
  namespace: courtstars
spec:
  type: ClusterIP
  selector:
    app: courtstars-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
