apiVersion: v1
kind: Service
metadata:
  name: courtstars-app
  namespace: courtstars
spec:
  type: NodePort
  selector:
    app: courtstars-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
